apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdtracker-groups
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdtracker-groups
  template:
    metadata:
      labels:
        app: bdtracker-groups
    spec:
      containers:
        - name: bdtracker-groups
          image: bdtracker.groups
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7771

---
apiVersion: v1
kind: Service
metadata:
  name: bdtracker-groups
spec:
  type: LoadBalancer
  ports:
    - name: bdtracker-groups
      port: 7771
      targetPort: 7771
  selector:
    app: bdtracker-groups
